# Generated by Django 5.2.8 on 2025-11-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("difficulty", models.CharField(max_length=20)),
                ("topic", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("solved_date", models.DateTimeField()),
            ],
        ),
    ]
